# Generated by Copilot on 2025-12-23
from django.db import migrations
import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import Point


def populate_location(apps, schema_editor):
    PointModel = apps.get_model('points', 'Point')
    for p in PointModel.objects.all():
        try:
            if p.latitude is not None and p.longitude is not None and p.location is None:
                p.location = Point(p.longitude, p.latitude, srid=4326)
                p.save(update_fields=['location'])
        except Exception:
            # Ignore if geometry backend not available; users will backfill later
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, null=True, blank=True),
        ),
        migrations.RunPython(populate_location, reverse_code=migrations.RunPython.noop),
    ]
