# Generated by Django 6.0 on 2025-12-24 20:28

from django.db import migrations
from django.contrib.gis.db import models as gis_models


def ensure_location_populated(apps, schema_editor):
    """Убедиться что у всех точек заполнен location из lat/lon"""
    Point = apps.get_model('points', 'Point')
    from django.contrib.gis.geos import Point as GEOSPoint
    
    for point in Point.objects.filter(location__isnull=True):
        if point.latitude is not None and point.longitude is not None:
            point.location = GEOSPoint(point.longitude, point.latitude, srid=4326)
            point.save(update_fields=['location'])


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_add_location'),
    ]

    operations = [
        # Сначала заполним location для всех существующих записей
        migrations.RunPython(ensure_location_populated, migrations.RunPython.noop),
        
        # Потом сделаем поле NOT NULL
        migrations.AlterField(
            model_name='point',
            name='location',
            field=gis_models.PointField(geography=True, srid=4326),
        ),
    ]
