# Generated by Django 6.0 on 2026-01-01 17:36

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_alter_message_point_alter_message_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=5000),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-created_at'], name='points_mess_created_4ebf2d_idx'),
        ),
        migrations.AddIndex(
            model_name='point',
            index=models.Index(fields=['latitude', 'longitude'], name='points_poin_latitud_136fe3_idx'),
        ),
    ]
